from enum import Enum


class GateOutcome(str, Enum):
    PASS = "PASS"
    FAIL = "FAIL"
    INCONCLUSIVE = "INCONCLUSIVE"
    BLOCKED = "BLOCKED"
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"


class ExecutionState(str, Enum):
    COMPLETE = "COMPLETE"
    BLOCKED = "BLOCKED"
    ERROR = "ERROR"


class ScientificState(str, Enum):
    FALSIFIED = "FALSIFIED"
    NOT_SUPPORTED = "NOT_SUPPORTED"
    SUPPORTED = "SUPPORTED"
    CERTIFIED_WITHIN_SCOPE = "CERTIFIED_WITHIN_SCOPE"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNRESOLVED = "UNRESOLVED"


class ValidityState(str, Enum):
    VALID = "VALID"
    OUTSIDE_DOMAIN = "OUTSIDE_DOMAIN"
    MODEL_INVALID = "MODEL_INVALID"
    DATA_INSUFFICIENT = "DATA_INSUFFICIENT"
    PROVENANCE_FAILURE = "PROVENANCE_FAILURE"
    TEMPORAL_FAILURE = "TEMPORAL_FAILURE"
    IDENTIFICATION_FAILURE = "IDENTIFICATION_FAILURE"


PROMOTABLE = {ScientificState.SUPPORTED.value, ScientificState.CERTIFIED_WITHIN_SCOPE.value}
CORE_GATES = tuple(f"G{i}" for i in range(16))
